apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: v9fi2g047-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v9fi2g047-python 
  name: v9fi2g047-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: v9fi2g047-python 
